<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MoviesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('movies')->insert([
            [
                'title' => 'Avatar 3: Fire and Ash',
                'description' => 'A new conflict erupts on the planet Pandora as the Na’vi face a fierce tribe connected to fire and ash.',
                'duration' => 197,
                'genre' => 'Sci-Fi, Adventure, Action',
                'release_date' => '2025-12-19',
                'poster_url' => 'posters/avatar.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=nb_fFj_0rq8',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Zootopia 2: A Shocking Mission',
                'description' => 'Nick and Judy return in a large-scale case that threatens the entire city of Zootopia.',
                'duration' => 128,
                'genre' => 'Animation, Adventure, Comedy',
                'release_date' => '2025-11-28',
                'poster_url' => 'posters/caotho.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=BjkIOU5PhyQ',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tom & Jerry: The Mysterious Compass',
                'description' => 'A mysterious compass unexpectedly opens a magical gateway, leading to a world full of challenges, laughter, and classic Tom & Jerry chases.',
                'duration' => 104,
                'genre' => 'Animation, Thriller, Adventure',
                'release_date' => '2026-01-01',
                'poster_url' => 'posters/tomjerry.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=W4bVSaeIzwI',
                'status' => 'coming_soon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Truy tim Long Dien Huong',
                'description' => 'The treasured artifact of a coastal village is stolen, triggering a thrilling journey to recover it. The film blends spectacular martial arts, humor, and deep human values.',
                'duration' => 111,
                'genre' => 'Comedy, Action',
                'release_date' => '2025-11-14',
                'poster_url' => 'posters/longdienhuong.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=-q1FYNMQBeU',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Now You See Me: Vanish and Reappear',
                'description' => 'The Four Horsemen officially return, teaming up with a new generation of Gen Z illusionists in the most daring diamond heist of their careers.',
                'duration' => 112,
                'genre' => 'Action, Crime, Thriller',
                'release_date' => '2025-11-28',
                'poster_url' => 'posters/phivutheky.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=QLKI8NKyeKo',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Thien Duong Mau',
                'description' => 'Thien Duong Mau is the first Vietnamese film depicting human trafficking scams abroad. Lured by promises of easy jobs and high salaries, many victims are imprisoned and forced to scam their own people.',
                'duration' => 120,
                'genre' => 'Action, Crime',
                'release_date' => '2025-12-31',
                'poster_url' => 'posters/thienduongmau.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=46ASchtBIbE',
                'status' => 'coming_soon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hoang Tu Quy',
                'description' => 'The story follows Than Duc, a prince born through dark magic. After escaping the forbidden palace, he seeks to free the Bone Demon from the Eye Gate to restore the Bone Demon Cult.',
                'duration' => 117,
                'genre' => 'Horror',
                'release_date' => '2025-12-05',
                'poster_url' => 'posters/hoangtuquy.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=Rc-0s7oeON8',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SpongeBob: The Pirate Curse',
                'description' => 'SpongeBob ventures into the deep sea to confront the ghost of the Flying Dutchman, overcoming challenges and uncovering mysterious secrets beneath the ocean.',
                'duration' => 96,
                'genre' => 'Comedy, Animation, Adventure',
                'release_date' => '2025-12-15',
                'poster_url' => 'posters/spongebob.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=XdPt8QWTypI',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Demon Slayer: Infinity Castle',
                'description' => 'The Demon Slayer Corps storms Infinity Castle to defeat Muzan. Tanjiro and the remaining Hashira must face the final members of the Twelve Kizuki.',
                'duration' => 155,
                'genre' => 'Action',
                'release_date' => '2026-01-29',
                'poster_url' => 'posters/thanhguomdietquy.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=rf0hW__Skow',
                'status' => 'coming_soon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Smurfs',
                'description' => 'When Papa Smurf is mysteriously kidnapped by the evil wizards Razamel and Gargamel, Smurfette leads the Smurfs into the real world to rescue him and save the universe.',
                'duration' => 92,
                'genre' => 'Animation, Comedy, Adventure',
                'release_date' => '2025-12-17',
                'poster_url' => 'posters/xitrum.png',
                'trailer_url' => 'https://www.youtube.com/watch?v=cSYyn_SijOc',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dragon Ball Super: Broly',
                'description' => 'Goku and Vegeta face Broly, a powerful Saiyan driven by rage, in an epic battle that shakes the fate of the universe.',
                'duration' => 102,
                'genre' => 'Action, Animation',
                'release_date' => '2025-12-29',
                'poster_url' => 'posters/dragonball.png',
                'trailer_url' => 'https://www.youtube.com/watch?v=FHgm89hKpXU',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
