<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MoviesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('movies')->insert([
            [
               'title' => 'Avatar 3: Lửa và tro tàn',
                'description' => 'Cuộc xung đột mới trên hành tinh Pandora khi người Na’vi đối mặt với một bộ tộc hung hãn liên quan đến lửa và tro tàn.',
                'duration' => 197,
                'genre' => 'Sci-Fi, Adventure, Action',
                'release_date' => '2025-12-19',
                'poster_url' => 'storage/photo/avatar.jpg',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(), 
            ],
            [
               'title' => 'ZOOTOPIA 2: PHI VỤ ĐỘNG TRỜI 2',
                'description' => 'Nick và Judy trở lại trong một vụ án quy mô lớn, đe dọa toàn bộ thành phố Zootopia.',
                'duration' => 128,
                'genre' => 'Animation, Adventure, Comedy',
                'release_date' => '2025-11-28',
                'poster_url' => 'storage/photo/caotho.jpg',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(), 
            ],
            [
               'title' => 'TOM & JERRY: CHIẾC LA BÀN KỲ BÍ',
                'description' => 'ĐẦU NĂM CƯỜI ĐÃ - TOM & JERRY ĐẠI NÁO RẠP VIỆT Một chiếc la bàn bí ẩn bất ngờ mở ra cánh cổng kỳ diệu - nơi đầy ắp thử thách, tiếng cười và những màn rượt đuổi “kinh điển” cộp mác Tom & Jerry.',
                'duration' => 104,
                'genre' => 'Animation, Thriller, Adventure',
                'release_date' => '2026-01-01',
                'poster_url' => 'storage/photo/tomjerry.jpg',
                'status' => 'coming_soon',
                'created_at' => now(),
                'updated_at' => now(), 
            ],
            [
               'title' => 'TRUY TÌM LONG DIÊN HƯƠNG',
                'description' => 'Báu vật làng biển Long Diên Hương bị đánh cắp, mở ra cuộc hành trình truy tìm đầy kịch tính. Không chỉ có võ thuật mãn nhãn, bộ phim còn mang đến tiếng cười, sự gắn kết và những giá trị nhân văn của con người làng chài.',
                'duration' => 111,
                'genre' => 'Comedy, Action',
                'release_date' => '2025-11-14',
                'poster_url' => 'storage/photo/longdienhuong.jpg',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(), 
            ],
            [
               'title' => 'PHI VỤ THẾ KỶ: THOÁT ẨN THOÁT HIỆN',
                'description' => 'Tứ Kỵ Sĩ chính thức tái xuất, bắt tay cùng các tân binh ảo thuật gia Gen Z trong một phi vụ đánh cắp kim cương liều lĩnh nhất trong sự nghiệp.',
                'duration' => 112,
                'genre' => 'Action, Crime, Thriller',
                'release_date' => '2025-11-28',
                'poster_url' => 'storage/photo/phivutheky.jpg',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(), 
            ],
            [
               'title' => 'THIÊN ĐƯỜNG MÁU',
                'description' => 'Thiên Đường Máu là phim điện ảnh đầu tiên về nạn lừa đảo người Việt ra nước ngoài. Tin lời hứa "việc nhẹ lương cao", không ít thanh niên bị đưa đến những "đặc khu", nơi họ trải qua cảnh giam lỏng và bị ép buộc phải gọi điện để lừa ngược lại chính đồng bào mình.',
                'duration' => 120,
                'genre' => 'Action, Crime',
                'release_date' => '2025-12-31',
                'poster_url' => 'storage/photo/thienduongmau.jpg',
                'status' => 'coming_soon',
                'created_at' => now(),
                'updated_at' => now(), 
            ],
            [
               'title' => 'HOÀNG TỬ QUỶ',
                'description' => 'Hoàng Tử Quỷ xoay quanh Thân Đức - một hoàng tử được sinh ra nhờ tà thuật. Trốn thoát khỏi cung cấm, Thân Đức tham vọng giải thoát Quỷ Xương Cuồng khỏi Ải Mắt Người để khôi phục Xương Cuồng Giáo.',
                'duration' => 117,
                'genre' => 'Horrified',
                'release_date' => '2025-12-05',
                'poster_url' => 'storage/photo/hoangtuquy.jpg',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(), 
            ],
            [
               'title' => 'SPONGEBOB: LỜI NGUYỀN HẢI TẶC',
                'description' => 'SpongeBob phiêu lưu xuống đáy đại dương để đối mặt với hồn ma của Người Hà Lan bay, vượt qua thử thách và khám phá những bí ẩn dưới biển.',
                'duration' => 96,
                'genre' => 'Comedy, Animation, Adventure',
                'release_date' => '2025-12-15',
                'poster_url' => 'storage/photo/spongebob.jpg',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(), 
            ],
            [
               'title' => 'THANH GƯƠM DIỆT QUỶ: VÔ HẠN THÀNH',
                'description' => 'Sát Quỷ Đoàn xông vào Vô Hạn Thành để đánh bại Muzan. Tuy nhiên, những Trụ Cột còn lại và những thành viên Sát Quỷ Đoàn sống sót sau khóa đào tạo cuối cùng và Tanjiro phải đối đầu với nhóm cuối trong Thập Nhị Quỷ trước.',
                'duration' => 155,
                'genre' => 'Action',
                'release_date' => '2026-01-29',
                'poster_url' => 'storage/photo/thanhguomdietquy.jpg',
                'status' => 'coming_soon',
                'created_at' => now(),
                'updated_at' => now(), 
            ],
            [
               'title' => 'Xì Trum',
                'description' => 'Khi Papa Smurf bị những phù thủy độc ác Razamel và Gargamel bắt cóc một cách bí ẩn, Smurfette phải dẫn dắt các Xì Trum đến thế giới thực để giải cứu ông. Với sự giúp đỡ của những người bạn mới, các Xì Trum phải khám phá ra điều gì định nghĩa số phận của họ để cứu vũ trụ.',
                'duration' => 92,
                'genre' => 'Animation, Comedy, Adventure',
                'release_date' => '2025-12-17',
                'poster_url' => 'storage/photo/xitrum.png',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(), 
            ],
            [
               'title' => 'DRAGON BALL SUPER: BROLY',
                'description' => 'Khi Papa Smurf bị những phù thủy độc ác Razamel và Gargamel bắt cóc một cách bí ẩn, Smurfette phải dẫn dắt các Xì Trum đến thế giới thực để giải cứu ông. Với sự giúp đỡ của những người bạn mới, các Xì Trum phải khám phá ra điều gì định nghĩa số phận của họ để cứu vũ trụ.',
                'duration' => 102,
                'genre' => 'Action, Animation',
                'release_date' => '2025-12-29',
                'poster_url' => 'storage/photo/dragonball.png',
                'status' => 'showing',
                'created_at' => now(),
                'updated_at' => now(), 
            ],
        ]);
    }
}
